/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as KonstruksiRouteImport } from './routes/konstruksi'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as KprRouteImport } from './routes/kpr'
import { Route as PertanahanRouteImport } from './routes/pertanahan'
import { Route as PetaRouteImport } from './routes/peta'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAgentRouteImport } from './routes/_authenticated/agent'
import { Route as AuthenticatedFavoritRouteImport } from './routes/_authenticated/favorit'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as LayananSlugRouteImport } from './routes/layanan.$slug'
import { Route as MediaSplatRouteImport } from './routes/media.$'
import { Route as PropertiIndexRouteImport } from './routes/properti.index'
import { Route as PropertiSlugRouteImport } from './routes/properti.$slug'
import { Route as UploadsSplatRouteImport } from './routes/uploads.$'
import { Route as ApiPublicCompanyVideoActiveRouteImport } from './routes/api/public/company-video.active'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const KonstruksiRoute = KonstruksiRouteImport.update({
  id: '/konstruksi',
  path: '/konstruksi',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const KprRoute = KprRouteImport.update({
  id: '/kpr',
  path: '/kpr',
  getParentRoute: () => rootRouteImport,
} as any)
const PertanahanRoute = PertanahanRouteImport.update({
  id: '/pertanahan',
  path: '/pertanahan',
  getParentRoute: () => rootRouteImport,
} as any)
const PetaRoute = PetaRouteImport.update({
  id: '/peta',
  path: '/peta',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentRoute = AuthenticatedAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritRoute = AuthenticatedFavoritRouteImport.update({
  id: '/favorit',
  path: '/favorit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananSlugRoute = LayananSlugRouteImport.update({
  id: '/layanan/$slug',
  path: '/layanan/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaSplatRoute = MediaSplatRouteImport.update({
  id: '/media/$',
  path: '/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiIndexRoute = PropertiIndexRouteImport.update({
  id: '/properti/',
  path: '/properti/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiSlugRoute = PropertiSlugRouteImport.update({
  id: '/properti/$slug',
  path: '/properti/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsSplatRoute = UploadsSplatRouteImport.update({
  id: '/uploads/$',
  path: '/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCompanyVideoActiveRoute =
  ApiPublicCompanyVideoActiveRouteImport.update({
    id: '/api/public/company-video/active',
    path: '/api/public/company-video/active',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/konstruksi': typeof KonstruksiRoute
  '/kontak': typeof KontakRoute
  '/kpr': typeof KprRoute
  '/pertanahan': typeof PertanahanRoute
  '/peta': typeof PetaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang': typeof TentangRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/favorit': typeof AuthenticatedFavoritRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/api/upload': typeof ApiUploadRoute
  '/layanan/$slug': typeof LayananSlugRoute
  '/media/$': typeof MediaSplatRoute
  '/properti/$slug': typeof PropertiSlugRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/properti/': typeof PropertiIndexRoute
  '/api/public/company-video/active': typeof ApiPublicCompanyVideoActiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/konstruksi': typeof KonstruksiRoute
  '/kontak': typeof KontakRoute
  '/kpr': typeof KprRoute
  '/pertanahan': typeof PertanahanRoute
  '/peta': typeof PetaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang': typeof TentangRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/favorit': typeof AuthenticatedFavoritRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/api/upload': typeof ApiUploadRoute
  '/layanan/$slug': typeof LayananSlugRoute
  '/media/$': typeof MediaSplatRoute
  '/properti/$slug': typeof PropertiSlugRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/properti': typeof PropertiIndexRoute
  '/api/public/company-video/active': typeof ApiPublicCompanyVideoActiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/konstruksi': typeof KonstruksiRoute
  '/kontak': typeof KontakRoute
  '/kpr': typeof KprRoute
  '/pertanahan': typeof PertanahanRoute
  '/peta': typeof PetaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang': typeof TentangRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/agent': typeof AuthenticatedAgentRoute
  '/_authenticated/favorit': typeof AuthenticatedFavoritRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/api/upload': typeof ApiUploadRoute
  '/layanan/$slug': typeof LayananSlugRoute
  '/media/$': typeof MediaSplatRoute
  '/properti/$slug': typeof PropertiSlugRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/properti/': typeof PropertiIndexRoute
  '/api/public/company-video/active': typeof ApiPublicCompanyVideoActiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/konstruksi'
    | '/kontak'
    | '/kpr'
    | '/pertanahan'
    | '/peta'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/tentang'
    | '/admin'
    | '/agent'
    | '/favorit'
    | '/profil'
    | '/api/upload'
    | '/layanan/$slug'
    | '/media/$'
    | '/properti/$slug'
    | '/uploads/$'
    | '/properti/'
    | '/api/public/company-video/active'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/konstruksi'
    | '/kontak'
    | '/kpr'
    | '/pertanahan'
    | '/peta'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/tentang'
    | '/admin'
    | '/agent'
    | '/favorit'
    | '/profil'
    | '/api/upload'
    | '/layanan/$slug'
    | '/media/$'
    | '/properti/$slug'
    | '/uploads/$'
    | '/properti'
    | '/api/public/company-video/active'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/konstruksi'
    | '/kontak'
    | '/kpr'
    | '/pertanahan'
    | '/peta'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/tentang'
    | '/_authenticated/admin'
    | '/_authenticated/agent'
    | '/_authenticated/favorit'
    | '/_authenticated/profil'
    | '/api/upload'
    | '/layanan/$slug'
    | '/media/$'
    | '/properti/$slug'
    | '/uploads/$'
    | '/properti/'
    | '/api/public/company-video/active'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  KonstruksiRoute: typeof KonstruksiRoute
  KontakRoute: typeof KontakRoute
  KprRoute: typeof KprRoute
  PertanahanRoute: typeof PertanahanRoute
  PetaRoute: typeof PetaRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TentangRoute: typeof TentangRoute
  ApiUploadRoute: typeof ApiUploadRoute
  LayananSlugRoute: typeof LayananSlugRoute
  MediaSplatRoute: typeof MediaSplatRoute
  PropertiSlugRoute: typeof PropertiSlugRoute
  UploadsSplatRoute: typeof UploadsSplatRoute
  PropertiIndexRoute: typeof PropertiIndexRoute
  ApiPublicCompanyVideoActiveRoute: typeof ApiPublicCompanyVideoActiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konstruksi': {
      id: '/konstruksi'
      path: '/konstruksi'
      fullPath: '/konstruksi'
      preLoaderRoute: typeof KonstruksiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpr': {
      id: '/kpr'
      path: '/kpr'
      fullPath: '/kpr'
      preLoaderRoute: typeof KprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pertanahan': {
      id: '/pertanahan'
      path: '/pertanahan'
      fullPath: '/pertanahan'
      preLoaderRoute: typeof PertanahanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peta': {
      id: '/peta'
      path: '/peta'
      fullPath: '/peta'
      preLoaderRoute: typeof PetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agent': {
      id: '/_authenticated/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AuthenticatedAgentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favorit': {
      id: '/_authenticated/favorit'
      path: '/favorit'
      fullPath: '/favorit'
      preLoaderRoute: typeof AuthenticatedFavoritRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan/$slug': {
      id: '/layanan/$slug'
      path: '/layanan/$slug'
      fullPath: '/layanan/$slug'
      preLoaderRoute: typeof LayananSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$': {
      id: '/media/$'
      path: '/media/$'
      fullPath: '/media/$'
      preLoaderRoute: typeof MediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properti/': {
      id: '/properti/'
      path: '/properti'
      fullPath: '/properti/'
      preLoaderRoute: typeof PropertiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properti/$slug': {
      id: '/properti/$slug'
      path: '/properti/$slug'
      fullPath: '/properti/$slug'
      preLoaderRoute: typeof PropertiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads/$': {
      id: '/uploads/$'
      path: '/uploads/$'
      fullPath: '/uploads/$'
      preLoaderRoute: typeof UploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/company-video/active': {
      id: '/api/public/company-video/active'
      path: '/api/public/company-video/active'
      fullPath: '/api/public/company-video/active'
      preLoaderRoute: typeof ApiPublicCompanyVideoActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAgentRoute: typeof AuthenticatedAgentRoute
  AuthenticatedFavoritRoute: typeof AuthenticatedFavoritRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAgentRoute: AuthenticatedAgentRoute,
  AuthenticatedFavoritRoute: AuthenticatedFavoritRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  KonstruksiRoute: KonstruksiRoute,
  KontakRoute: KontakRoute,
  KprRoute: KprRoute,
  PertanahanRoute: PertanahanRoute,
  PetaRoute: PetaRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TentangRoute: TentangRoute,
  ApiUploadRoute: ApiUploadRoute,
  LayananSlugRoute: LayananSlugRoute,
  MediaSplatRoute: MediaSplatRoute,
  PropertiSlugRoute: PropertiSlugRoute,
  UploadsSplatRoute: UploadsSplatRoute,
  PropertiIndexRoute: PropertiIndexRoute,
  ApiPublicCompanyVideoActiveRoute: ApiPublicCompanyVideoActiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
